### ISSUE TITLE
Why not the latest version of trackmania?

### ISSUE THREAD

**Issue by mileseverett** [pb4git/trackmania_rl_public#8]
As someone with ml experience but not rl experience, why did you go for trackmania NF rather than the latest version? Seems there is a nice interface here: https://github.com/trackmania-rl/tmrl

**Comment by pb4git** [comment]
While tmrl is an awesome project, it is built as a *real-time* gym environment.
What real-time means, is that the observation happens, then the AI calculates its moves, sends the command while the game engine is still running. This introduces random delays before / after an action.
We felt that the difficulty of writing a Trackmania AI was large enough, and did not want to tackle the real-time aspect.

To remove the real-time aspect, we tap into the game engine and pause/unpause every action. This is done is tm_interface_manager.py . The method uses a plugin called TMInterface, which is only available for TMNF, that's why we're not using the latest Trackmania version.

**Comment by mileseverett** [comment]
Ah got it. Thanks for the explanation
